project:
  type: website

website:
  title: "Comp. Soc. Sci. for Sustainability (EBS 181/281)"
  favicon: Logo.png
  navbar:
    background: "#8C1515"
    foreground: "#FFFFFF"
    right:
      - href: index.qmd
        text: Syllabus
 
      - href: notes/index.qmd
        text: Course Notes

      - href: lectures/index.qmd
        text: Lectures

#      - href: psets/index.qmd
#        text: "Problem sets"

#      - href: https://mt.digital
#        text: "MA Turner, Ph.D."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: /users/mt/workspace/Writing/library.bib
