---
title: "Computational Social Science for Sustainability (EBS 181/281)"
editor: 
  markdown: 
    wrap: 80
---

## Winter 2025 {.unlisted}

### Schedule and location

Monday lectures and Wednesday lab sections 11:30 AM - 12:50 PM in
[320-109](https://campus-map.stanford.edu/?srch=320-109#), [Winter quarter
2025](https://studentservices.stanford.edu/calendar/academic-dates/stanford-academic-calendar-2024-2025#winter25).

### Instructor

Dr. Matthew A. Turner, PhD ([email](mailto:maturner@stanford.edu))

Feel free to call me by my first name.

Please see my [professional site](https://mt.digital) to learn more about me.

### Office hours {#office-hours}

-   Monday and Tuesday 1 - 3 PM (Y2E2 352)
-   Thursday 3 - 4 PM (Zoom; link to be shared on Canvas)
-   By appointment

### Getting help

I recommend seeking help early if students feel stuck or lost. Please attend
[office hours](#office-hours), [email me](mailto:maturner@stanford.edu) to ask
questions or set up a time to meet, or seek the help from other students.

## Course overview

The development and diffusion of sustainable innovations, cooperation for
sustainable resource management, and political polarization that can undermine
these, share a common explanation: these phenomena all emerge from repeated
social interactions between individuals over time. These interactions take the
form of social learning, social influence, or strategic economic cooperation.

Take this course to learn how to develop computational "experiments" of repeated
social interaction that can be used to design more effective sustainability
interventions and analyze behavioral data. Students will learn transferrable technical
skills in programming and mathematics. Students will deepen their interdisciplinary
understanding of from the social and behavioral sciences. With these skills and understanding, students will be empowered to create research products that analyze and evaluate potential sustainability interventions using computation.

### Learning goals

Through participation in lecture and lab sections and completion of course
activities, students will

-   learn modern approaches to scientific modeling and statistical analysis of social behavior
-   learn to develop, implement, and analyze their own models for designing
    sustainability interventions
-   learn to write effective research papers using the Introduction, Model,
    Analysis, Discussion structure
-   improve their R programming skills, including the popular
    [`tidyverse`](https://www.tidyverse.org/), for simulation modeling and data science (see the R for Data Science book)[https://r4ds.hadley.nz/] for more details.


### Expectations

Understanding mutual expectations can help everyone succeed. There are things you can expect of me and things I expect of enrolled students.

#### What you can expect of me

I will do my best to promote an encouraging, safe, and fair learning environment to
promote student success. I will strive to understand and support student career
goals coming from a diversity of life experiences.

You can expect I will be eager to help when needed, especially if you start from very little to no experience with math and programming. I understand that these subjects can cause anxiety for some.

#### Expectations of all students

Students are expected attend all scheduled course meetings unless there are extenuating circumstances. Please email if this occurs. Students are expected to seek help if they are struggling or stuck.

#### Expectations of graduate students

Graduate students will be required to complete an extra exercise on each problem
set that will be extra credit for undergraduates. They will be held to higher standards for clarity, structure, and technical detail in midterm and final projects.


### Course materials

Students will need a laptop or otherwise portable computer to bring to the
Wednesday lab sections. There are a number of readings from journals and books
(see the [Calendar](/#Calendar) below), but these are either available through
Stanford Libraries, or if not I will provide PDF copies via Canvas.

## Course structure

Each week will have a Monday lecture on topics in computational social science
for sustainability. Wednesday meetings will focus on developing programming,
analysis, and writing skills in an interactive lab-section setting. In these
Wednesday sections students will be introduced to problem sets and midterm and
final projects, and have time to ask questions of and work together with the
instructor and peers.

### Coursework and Grading

Students will be evaluated based on their completion of six assignments worth 100 points total:
four problem sets (10 points each), a midterm project (20 points), and a final project (40 points). Undergraduate
students will have the opportunity for bonus points on each problem set.  

-   **Problem sets:** There will be four problem sets introduced on Wednesdays
    during the computing lab section. Students will also have the opportunity to
    work together and ask the instructor questions during other lab sections
    before each assignment is due. (10 points per problem set)
-   **Midterm project:** Students will write a report on how they will use a
    model from the course to address a sustainability problem of interest. The
    midterm project will be used as a foundation for the final project. (20
    points)
-   **Final project:** Students will expand on their midterm project, performing
    a detailed model analysis and discussing the implications of their results
    for designing sustainability interventions. (40 points)

### Late coursework policy

If there is a family or health emergency or other acute distress please contact
me to make arrangements to submit late work without penalty. Otherwise the
following policy applies: 

- Problem sets up to 72 hours late can receive 50%
credit. 
- Problem sets up to one week late can receive 20% credit.
- The midterm project may be submitted up to one week late to receive 50% credit.
- The final project may not be submitted late.
- No credit will be given for work beyond one week late.



## Lecture and lab calendar and topics outline

### Calendar

In the calendar below, PS stands for _problem set_. Subject to change.

<table class="table table-sm">
  <caption>
  <thead>
    <tr>
      <th text-align: center scope="col" width="100">Week</th>
      <th scope="col">Topic</th>
      <th scope="col">Coursework</th>
      <th scope="col">Readings</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1, M 1/6 and W 1/8</td>
      <td>What is social science, why _computation_, and how these can promote sustainability in socio-ecological systems.</td>
      <td><ul><li>**PS 1, diffusion via social learning:** How many individuals need to be know about beneficial sustainable innovations so that they spread throughout a population? **Due 1/22 at 11:30 AM**</li></ul></td>
      <td>
        <ul>
          <li>@PisorLansingMagargal2023</li>
          <li>@Ostrom2014</li>
          <li>@Cox2010</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>2, M 1/13 and W 1/15</td>
      <td>The effect of social networks on sustainable innovation development and diffusion.</td>
      <td></td>
      <td><ul><li>@Pisor2024</li><li>@Centola2022</li><li>@Derex2016</li></ul></td>
    </tr>
    <tr>
      <td>3, M 1/20 and W 1/22</td>
      <td>How asymmetric preferences for within-group interaction can create sustainability-promoting social networks, and how to measure this in the real world.</td>
      <td><ul><li>**PS 1 due 1/22 at 11:30 AM**</li><li>**PS 2, how information and opinions spread in different social networks:** How careful timing of informational interventions can help limit polarization. **Due 2/5 at 11:30 AM**</li></ul></td>
      <td>@Turner2023</td>
    </tr>
    <tr>
      <td>4, W 1/29 (no class M 1/27)</td>
      <td>Social influence represented as forces causing opinion dynamics.</td>
      <td></td>
      <td>@Turner2018; Smaldino (2023; Ch. 6)</td>
  </tr>
  <tr>
    <td>5, M 2/3 and W 2/5</td>
    <td>Opinion dynamics in the context of sustainability. Experimental design and measurement in opinion dynamics experiments.</td>
    <td><ul><li>**PS 2 due W 2/5 at 11:30 AM**</li><li>**Midterm project announced W 2/5, due 2/24 at 11:59 PM**</li></ul></td>
    <td><ul><li>@Liddell2018</li><li>@GalesicEtAl2023</li></ul></td>
  </tr>
  <tr>
    <td>6, M 2/10 and W 2/12</td>
    <td>Common-pool resource management dilemmas: when and why do people cooperate? (Part I)</td>
    <td><ul><li>**PS 3, modeling and measuring socio-ecological dilemmas:** applications include groundwater management and reforestation.**Due W 2/26 at 11:30 AM**</li></ul></td>
    <td><ul><li>@Nowak2006</li><li>@Andrews2018</li></ul></td>
  </tr>
  <tr>
    <td>7, W 2/19 (no class M 2/17)</td>
    <td>Common-pool resource management dilemmas: when and why do people cooperate? (Part II)</td>
    <td><ul><li>**Final project announced, due M 3/17 at 11:59 PM**</li></ul></td>
    <td><ul><li>@Tavoni2011</li><li>@Jackson2008, Ch. 9, especially 9.2 and 9.3</li></ul></td>
  </tr>
  <tr>
    <td>8, M 2/24 and W 2/26</td>
    <td>How to perform and report computational social model analyses.</td>
    <td><ul><li>**PS 3 due W 2/26 at 11:30 AM**</li><li>**PS 4, the evolution of institutions for sustainable property rights:** with example of promoting carbon-capture farming. **Due W 3/12 at 11:30 AM**</li></ul></td>
    <td></td>
  </tr>
  <tr>
    <td>9, M 3/3 and W 3/5</td>
    <td>Common-pool resource management dilemmas: when and why do people cooperate? (Part II)</td>
    <td></td>
    <td><ul><li>@Waring2015</li><li>@Waring2017</li><li>@Andrews2024</li></ul></td>
  </tr>
  <tr>
    <td>10, M 3/10 and W 3/12</td>
    <td>Review: A look back at how computational social science can promote sustainability, through the lens of the Price equation.</td>
    <td><ul><li>**PS 4 Due W 3/12**</li><li>**Final project due W 3/5 at 11:30 AM**</li></ul></td>
    <td><ul><li>@Deffner2024</li><li>@Bak-Coleman2021</li></ul></td>
  </tr>

  </tbody>
</table>

### Course outline

1.  Computational social science can help design sustainability interventions.
    Social science theory provides models of repeated human interaction over
    time that can be used, for example, to represent [Ostrom's eight "design
    principles" for sustainable socio-ecological
    systems](https://earthbound.report/2018/01/15/elinor-ostroms-8-rules-for-managing-the-commons/).

    -   Lab: Introducing the *80% success rate* exercise, "How much advertising
        is necessary for an 80% success rate in spreading a sustainable
        innovation in groups, given population size and average number of
        acquaintances of people in the group?"

2.  How human psychology, groups, and social networks can promote or inhibit the
    diffusion of sustainable innovations, Part I: single-group social networks.

    -   Lab: Could innovation-supporting social networks also promote inequality
        [@Moser2023]?

3.  How human psychology, groups, and social networks can promote or inhibit the
    diffusion of sustainable innovations, Part II: two-group (or more) social
    networks, i.e., *metapopulation* social networks.

    -   Lab I: 80% success rate exercise with two-group social networks defined
        by each group's *homophily* level, i.e., tendency of group members to
        interact with others from their own group [@Turner2023].

    -   Lab II: Use stochastic block model to infer networks from data
        [@DeBacco2023; @Ross2024].

4.  Social influence: understanding the effect of rhetoric as a force that acts
    on opinions and beliefs. How to measure opinion dynamics and

    -   Lab I: When is polarization path-dependent and therefore possible to
        avoid [@Turner2018]?
    -   Lab II: Opinion dynamics measurement depends on accurate inference using
        categorical (Likert-style) observational data [@Liddell2018].

5.  The emergence of cooperation via reciprocity: application to groundwater
    sustainability. How to predict and restrict potential free-riding based on
    marginal utility in managing common pool resources using game theory (see
    @Jackson).

    -   Lab I: "Groundwater sharing dilemma" (as we'll call it, though it's just
        a re-telling of the famous [prisoners'
        dilemma](https://en.wikipedia.org/wiki/Prisoner%27s_dilemma))
    -   Lab II: Agent-based model of behavioral study of "avoidance of
        disastrous climate change in a public goods game" by @Tavoni2011

6.  Ideal institutions support human cooperation by balancing variation and
    maintenance of beneficial behaviors within and between stakeholder groups
    [@Richerson2016d; @Waring2015]. Example: sustainable agricultural practices
    like crop switching [@Waring2023; @Kling2024].

    -   Lab I: The evolution of property rights supports sustainability
        [@Waring2017]. What sorts of social networks evolve? Could alternatives
        better promote or inhibit the development and diffusion of innovations?
